<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Product Pricing & Costing</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><link rel="stylesheet" href="/styles.css"></head><body><div class="app-shell"><aside class="sidebar"><h4>Costing Suite</h4><p>Product Pricing & Costing</p><button data-section="dashboard" class="nav-btn active">Dashboard</button><button data-section="vendors" class="nav-btn">Vendors</button><button data-section="rawMaterials" class="nav-btn">Raw Materials</button><button data-section="rawPurchases" class="nav-btn">Raw Purchases</button><button data-section="packaging" class="nav-btn">Packaging Materials</button><button data-section="packagingPurchases" class="nav-btn">Packaging Purchases</button><button data-section="products" class="nav-btn">Products</button><button data-section="calculator" class="nav-btn">Pricing Calculator</button><button data-section="history" class="nav-btn">Pricing History</button></aside><main class="content">
<section id="dashboardSection" class="app-section"><div class="page-head"><h2>Dashboard</h2><span>Overview of products, vendors, purchases, and recent pricing</span></div><div id="dashboardCards" class="metrics"></div><div class="grid-2"><div class="panel"><h5>Recent Purchases</h5><div class="table-responsive"><table id="recentPurchases" class="table table-sm"></table></div></div><div class="panel"><h5>Recent Pricing Calculations</h5><div class="table-responsive"><table id="recentPricing" class="table table-sm"></table></div></div></div></section>
<section id="vendorsSection" class="app-section d-none"><div class="section-bar"><h2>Vendor Master</h2><button class="btn btn-primary" data-add="vendors">Add Vendor</button></div><input id="vendorSearch" class="form-control mb-3" placeholder="Search vendors"><table id="vendorsTable" class="table table-striped"></table></section>
<section id="rawMaterialsSection" class="app-section d-none"><div class="section-bar"><h2>Raw Material Master</h2><button class="btn btn-primary" data-add="raw_materials">Add Raw Material</button></div><table id="rawMaterialsTable" class="table table-striped"></table></section>
<section id="rawPurchasesSection" class="app-section d-none"><div class="section-bar"><h2>Raw Material Purchases</h2><button class="btn btn-primary" data-add="raw_material_purchases">Record Purchase</button></div><table id="rawPurchasesTable" class="table table-striped"></table></section>
<section id="packagingSection" class="app-section d-none"><div class="section-bar"><h2>Packaging Material Master</h2><button class="btn btn-primary" data-add="packaging_materials">Add Packaging</button></div><table id="packagingTable" class="table table-striped"></table></section>
<section id="packagingPurchasesSection" class="app-section d-none"><div class="section-bar"><h2>Packaging Purchases</h2><button class="btn btn-primary" data-add="packaging_purchases">Record Purchase</button></div><table id="packagingPurchasesTable" class="table table-striped"></table></section>
<section id="productsSection" class="app-section d-none"><div class="section-bar"><h2>Product Master</h2><button class="btn btn-primary" data-add="products">Add Product</button></div><table id="productsTable" class="table table-striped"></table></section>
<section id="calculatorSection" class="app-section d-none"><div class="page-head"><h2>Product Pricing Calculator</h2><span>Variant-wise landing cost → MRP → customer and dealer prices</span></div><form id="pricingForm" class="calculator panel"><div class="row g-3"><div class="col-md-4"><label>Product</label><select name="product_id" id="calcProduct" class="form-select" required></select></div><div class="col-md-5"><label>Raw Material Purchase</label><select name="raw_material_purchase_id" id="calcPurchase" class="form-select" required></select></div><div class="col-md-3"><label>Notes</label><input name="notes" class="form-control"></div></div><div id="purchaseSnapshot" class="snapshot"></div><h4 class="mt-4">Variants</h4><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Variant</th><th>Qty</th><th>Unit</th><th>Packaging</th><th>Sticker</th><th>Labour</th><th>Profit %</th><th>Cust Type</th><th>Cust Disc</th><th>Dealer %</th><th>Landing</th><th>MRP</th><th>Customer SP</th><th>Dealer</th><th></th></tr></thead><tbody id="variantRows"></tbody></table></div><button type="button" id="addVariant" class="btn btn-outline-primary">+ Add Variant</button><button class="btn btn-success ms-2">Save Calculation</button></form></section>
<section id="historySection" class="app-section d-none"><div class="section-bar"><h2>Pricing History</h2><button id="refreshHistory" class="btn btn-outline-primary">Refresh</button></div><table id="historyTable" class="table table-striped"></table></section>
</main></div><div class="modal fade" id="crudModal" tabindex="-1"><div class="modal-dialog modal-lg"><form id="crudForm" class="modal-content"><div class="modal-header"><h5 id="crudTitle"></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div id="crudBody" class="modal-body"></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div><div id="toast" class="toast-msg"></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="app.js"></script></body></html>
